name: Deploy to Vercel and Expo

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy-web:
    runs-on: ubuntu-latest
    name: Deploy Web App to Vercel
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build web app
        run: node build-web.js

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
          vercel-args: '--prod'

  deploy-mobile:
    runs-on: ubuntu-latest
    name: Deploy Mobile App to Expo
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Install Expo CLI
        run: npm install -g @expo/cli

      - name: Build and publish to Expo
        run: |
          expo publish --platform all
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
